mail:
    imap:
        host: ${MAIL_IMAP_HOST}
        port: ${MAIL_IMAP_PORT}
        username: ${MAIL_IMAP_USERNAME}
        password: ${MAIL_IMAP_PASSWORD}
        enabled: true
        folder: INBOX
        mark-as-seen: true
        poll-interval: 1s
        ssl: true
        mode: idle
gmail:
    client-id: ${GMAIL_CLIENT_ID}
    client-secret: ${GMAIL_CLIENT_SECRET}
    refresh-token: ${GMAIL_REFRESH_TOKEN}
ai:
    provider: ${AI_PROVIDER:groq}
openai:
    base-url: ${OPENAI_API_URL}
    api-key: ${OPENAI_API_KEY}
    model: ${OPENAI_API_MODEL}
    store: true
groq:
    api-key: ${GROQ_API_KEY}
    model: ${GROQ_API_MODEL}
    base-url: ${GROQ_API_URL}
spring:
    application:
        name: mind
    datasource:
        url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
        username: ${PGUSER}
        password: ${PGPASSWORD}
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        open-in-view: false
        properties:
            hibernate:
                jdbc:
                    time_zone: Europe/Berlin
                dialect: org.hibernate.dialect.PostgreSQLDialect
